{{- if eq .Values.deployProfile "dev" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.formManagementModeler.name }}
  name: {{ .Values.formManagementModeler.name }}
spec:
  host: {{ .Values.formManagementModeler.name }}-{{ .Values.cdPipelineName }}-{{ .Values.cdPipelineStageName }}.{{ .Values.dnsWildcard }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.formManagementModeler.name }}
    weight: 100
status:
  ingress: []
{{- end }}
