apiVersion: v1
data:
  username: {{ .Values.formManagementModeler.credentials.username | b64enc | quote }}
  password: {{ .Values.formManagementModeler.credentials.password | b64enc | quote }}
  #password: {{ randAlphaNum 12 | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: {{ .Values.formManagementModeler.name }}-credentials
type: Opaque
