{{- if eq .Values.global.deploymentMode "development" }}
apiVersion: v1
data:
  username: {{ .Values.formManagementModelerDb.credentials.username | b64enc | quote }}
  password: {{ randAlphaNum 12 | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: {{ .Values.formManagementModeler.name }}-db-credentials
type: Opaque
{{- end }}
