{{- if eq .Values.global.deploymentMode "development" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.formManagementModeler.name }}
  labels:
    app: {{ .Values.formManagementModeler.name }}
spec:
  {{- if .Values.formManagementModeler.service.clusterIP }}
  clusterIP: {{ .Values.formManagementModeler.service.clusterIP }}
  {{- end }}
  ports:
    - name: ui
      {{- if eq .Values.formManagementModeler.service.type "NodePort" }}
      nodePort: {{ .Values.formManagementModeler.service.nodePort }}
      {{- end }}
      port: {{ .Values.formManagementModeler.service.port }}
      targetPort: {{ .Values.formManagementModeler.port }}
  selector:
    app: {{ .Values.formManagementModeler.name }}
  type: "{{ .Values.formManagementModeler.service.type }}"
{{- end }}
